### PR TITLE
Create LICENSE

### LINKED ISSUE #2: Add a LICENSE
Hello, 
Thank you for creating this module. 
The repository is missing a license -MIT that is mentioned in pyproject
https://github.com/indigoviolet/conda-pip-minimal/blob/a4c69d168a085bf3f80aff440530676f73eb9a0c/pyproject.toml#L5
Would like to make this available as a conda-package on condaforge.
I can help with the conda package / conda-forge distribution.

### PR DESCRIPTION
**Pull request by rxm7706**
Fixes https://github.com/indigoviolet/conda-pip-minimal/issues/2

- Add License MIT
- Add conda recipe
- Clean up and standardize .ignore from github python .ignores
- remove /src root directory to python package as root dir
- add floors and roofs for package limits and standarize for conda and pip

### CODE REVIEW

**Comment by joshdunnlime** [comment]
@indigoviolet and @rxm7706
I have added you both as maintainers in the conda package for `conda-pip-minimal`. If you are happy to have your names added please leave a comment in this PR saying so. If not, let me know here and I will remove your names from there :)

https://github.com/conda-forge/staged-recipes/pull/26100

**Comment by rxm7706** [comment]
Thank you @joshdunnlime - Happy to help as a co-maintainer.

**Review by joshdunnlime — APPROVED** [review]

**Comment by joshdunnlime** [comment]
@indigoviolet
Are you happy with these changes? Mostly it is a couple small tidy-ups compared with what @rxm7706 did.
- We needed to add the MIT LICENSE.txt to package itself to satisfy the MIT license and therefore the conda-forge checks (see [here](https://github.com/conda-forge/staged-recipes/pull/26100#issuecomment-2068953412)).

Assuming you are happy for this change to be merged, how do we go about deploying to pypi? We will need a version 0.2.2 to add the license (without changing 0.2.1).

I also plan to pick up some of the options in your [DEV-NOTES](https://github.com/indigoviolet/conda-pip-minimal/blob/main/NOTES.org#dev-notes) and try and fix the Issues I have raised: #4 #5.

**Review by indigoviolet — APPROVED** [review]
Looks good!

**Pull request merged**
